# Generated by Django 3.1.1 on 2020-12-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyinghistory',
            name='stripe_id',
            field=models.CharField(max_length=200, verbose_name='ID'),
        ),
    ]
